# Generated by Django 6.0.2 on 2026-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_photo_studentcertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
