# Generated by Django 6.0.2 on 2026-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='N/A'),
        ),
    ]
