# Generated by Django 6.0.2 on 2026-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transport',
            field=models.CharField(choices=[('BUS', 'Bus'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
