# Generated by Django 4.2.25 on 2026-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_penaltysetting_invoice_penalty_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elementary_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bus_transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('KG', 'KG'), ('ELEMENTARY', 'Elementary')], default='KG', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.CharField(choices=[('BUS', 'Bus'), ('FOOT', 'Foot')], default='FOOT', max_length=10),
        ),
    ]
