# Generated by Django 4.2.25 on 2026-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentfeesetting_student_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('KG1', 'KG 1'), ('KG2', 'KG 2'), ('KG3', 'KG 3'), ('GRADE1', 'Grade 1'), ('GRADE2', 'Grade 2'), ('GRADE3', 'Grade 3'), ('GRADE4', 'Grade 4'), ('GRADE5', 'Grade 5'), ('GRADE6', 'Grade 6'), ('GRADE7', 'Grade 7'), ('GRADE8', 'Grade 8')], default='KG1', max_length=20),
        ),
    ]
