# Generated by Django 4.2.25 on 2026-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCapacitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('KG1', 'KG 1'), ('KG2', 'KG 2'), ('KG3', 'KG 3'), ('GRADE1', 'Grade 1'), ('GRADE2', 'Grade 2'), ('GRADE3', 'Grade 3'), ('GRADE4', 'Grade 4'), ('GRADE5', 'Grade 5'), ('GRADE6', 'Grade 6'), ('GRADE7', 'Grade 7'), ('GRADE8', 'Grade 8')], max_length=20, unique=True)),
                ('max_students_per_section', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade_level'],
            },
        ),
    ]
