# Generated by Django 4.2.25 on 2026-02-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_schoolaccount_ledgerentry_expenserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dashboardnotification',
            name='category',
            field=models.CharField(choices=[('PAYROLL_REQUEST', 'Payroll Request'), ('PAYROLL_APPROVAL', 'Payroll Approval'), ('PAYROLL_REJECTION', 'Payroll Rejection'), ('PAYROLL_PAID', 'Payroll Paid'), ('ANNOUNCEMENT', 'Announcement'), ('DRIVER_DELAY', 'Driver Delay'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('GARAGE', 'Garage'), ('MATERIAL', 'Material'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PARENTS', 'Parents'), ('STAFF', 'Staff'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('reason', models.CharField(choices=[('GENERAL', 'General'), ('CROWD', 'Traffic/Crowd'), ('FUEL', 'Fuel'), ('GARAGE', 'Garage'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
