# Generated by Django 4.2.25 on 2026-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expenserequest_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('STUDENT_FEE', 'Student Fee'), ('REGISTRATION_FEE', 'Registration Fee'), ('TRANSPORT_FEE', 'Transport Fee'), ('MONTHLY_FEE', 'Monthly Fee'), ('MANUAL_INCOME', 'Manual Income'), ('SALARY_PAYMENT', 'Salary Payment'), ('EXPENSE_PAYMENT', 'Expense Payment'), ('CREDIT_GIVEN', 'Credit Given'), ('CREDIT_REPAYMENT', 'Credit Repayment'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
