# Generated by Django 4.2.25 on 2026-04-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(blank=True, default='', max_length=120)),
                ('swift_code', models.CharField(blank=True, default='', max_length=50)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bank_name', 'account_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.bankaccount'),
        ),
    ]
