# Generated by Django 4.2.25 on 2026-04-04 18:49

from django.db import migrations, models

def set_cbe_as_default(apps, schema_editor):
    BankAccount = apps.get_model('finance', 'BankAccount')
    if BankAccount.objects.filter(is_default=True).exists():
        return
    cbe_account = BankAccount.objects.filter(
        is_active=True,
        bank_name__iexact='Commercial Bank of Ethiopia',
    ).order_by('id').first()
    if cbe_account:
        cbe_account.is_default = True
        cbe_account.save(update_fields=['is_default'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_bankaccount_ledgerentry_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_cbe_as_default, migrations.RunPython.noop),
    ]
